"""Inference handshake: the contract a closure exposes to Bayesian calibration.

FROZEN minimal interface (foundation freeze, core-v1.0). One planned revision
after Phase 1. Consumers import these names and do not edit this file (see the
root CLAUDE.md working rule on frozen interfaces).

The handshake is the trio every closure exposes so the existing MCMC/HMC and
Kennedy-O'Hagan (KOH) calibration layer can drive any closure uniformly:

  1. parameter_spec() -> ParameterSpec
        coefficient names, literature defaults, and the realizability + stability
        bounds (the truncation box the prior lives in).
  2. prior()          -> ClosurePrior
        a prior over those coefficients, INCLUDING the fluctuation-dissipation
        coupling hook. For a memoryless closure (SST) the hook is inert. For a
        generalized Langevin closure it ties the memory-kernel parameters to the
        noise parameters through the second fluctuation-dissipation theorem,

            K(s) proportional to (F(s), F(0)),                          (FD-2)

        so memory and noise are never specified independently.
  3. a likelihood hook mapping parameters to predicted statistics:
        Likelihood.predict(theta) -> Prediction(statistics, status)
        The predicted statistics eta = H(theta) are what the KOH likelihood
        compares to data,  y = eta + delta + epsilon  (delta = model discrepancy).

House style: class-based, no dataclass, no try/except. A failed evaluation is
classified by EvaluationStatus and returned, never raised, mirroring the existing
C++ ForwardModel return-code contract.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from enum import Enum

import numpy as np


class EvaluationStatus(Enum):
    """Classification of a single forward evaluation.

    Mirrors rans_sst_py.EvaluationStatus so a C++ result maps onto it by name.
    Failure is a returned status, not an exception.
    """

    Converged = "Converged"
    Unconverged = "Unconverged"
    DivergenceDetected = "DivergenceDetected"
    InvalidParameters = "InvalidParameters"
    Unknown = "Unknown"

    @staticmethod
    def coerce(value) -> "EvaluationStatus":
        """Map a C++ enum, a string, or an EvaluationStatus onto this enum.

        Bare success strings used by the Python forward-model wrappers
        ("ok", "precomputed", "surrogate", "external") count as Converged.
        """
        if isinstance(value, EvaluationStatus):
            return value
        name = getattr(value, "name", None)
        if name is None:
            name = str(value).split(".")[-1]
        for s in EvaluationStatus:
            if s.name == name or s.value == name:
                return s
        if str(value).lower() in ("ok", "precomputed", "surrogate", "external"):
            return EvaluationStatus.Converged
        return EvaluationStatus.Unknown

    def is_usable(self) -> bool:
        """Only a converged result is fully usable; the rest are down-weighted."""
        return self is EvaluationStatus.Converged


class ParameterSpec:
    """Names, defaults, and realizability + stability bounds of the inferred
    closure coefficients.

    The [lower, upper] box is the admissible region set by coefficient
    positivity and numerical-stability limits; the prior is truncated to it.
    ``defaults`` are the literature reference values (for SST, Menter 1994).
    """

    def __init__(self, names, defaults, lower, upper):
        self.names = [str(n) for n in names]
        self.defaults = np.asarray(defaults, dtype=np.float64)
        self.lower = np.asarray(lower, dtype=np.float64)
        self.upper = np.asarray(upper, dtype=np.float64)
        n = len(self.names)
        if not (self.defaults.shape == (n,) and self.lower.shape == (n,)
                and self.upper.shape == (n,)):
            raise ValueError(
                "ParameterSpec: names, defaults, lower, upper must share length "
                f"({n}, {self.defaults.shape}, {self.lower.shape}, {self.upper.shape})"
            )
        if np.any(self.lower > self.upper):
            raise ValueError("ParameterSpec: lower bound exceeds upper bound")

    @property
    def n(self) -> int:
        return len(self.names)

    def in_bounds(self, theta) -> bool:
        theta = np.asarray(theta, dtype=np.float64)
        if theta.shape != (self.n,) or not np.all(np.isfinite(theta)):
            return False
        return bool(np.all(theta >= self.lower) and np.all(theta <= self.upper))

    def clip(self, theta) -> np.ndarray:
        """Clip theta into the realizability + stability box."""
        return np.clip(np.asarray(theta, dtype=np.float64), self.lower, self.upper)


class FluctuationDissipationCoupling(ABC):
    """The second fluctuation-dissipation theorem as a prior coupling memory and
    noise parameters: K(s) proportional to (F(s), F(0))  (FD-2).

    A memoryless closure has no such coupling (use None as the prior's hook). A
    generalized Langevin closure implements ``log_density`` to add the coupling
    term to the log-prior, and may implement ``project`` to derive the noise
    parameters from the memory parameters so the two are never independent.
    """

    @abstractmethod
    def log_density(self, theta: np.ndarray, spec: ParameterSpec) -> float:
        """Additive log-prior term coupling the memory and noise components."""

    def project(self, theta: np.ndarray, spec: ParameterSpec) -> np.ndarray:
        """Optional hard map enforcing the FD relation (default: identity)."""
        return np.asarray(theta, dtype=np.float64)


class ClosurePrior:
    """Truncated-normal prior over closure coefficients plus the FD coupling hook.

    Base term (matching the existing priors.Prior): independent truncated normals
    centred on ``spec.defaults`` with std ``relative_std * |defaults|``, truncated
    to the realizability + stability box [spec.lower, spec.upper]:

        log p(theta) = -0.5 * sum_i ((theta_i - mu_i) / sigma_i)^2   inside the box
                     = -inf                                          outside the box

    FD term: when ``fd_coupling`` is set its log_density is added, tying the memory
    kernel to the noise autocorrelation (FD-2). For SST, fd_coupling is None.
    """

    def __init__(self, spec: ParameterSpec, stds=None, relative_std: float = 0.15,
                 fd_coupling: "FluctuationDissipationCoupling" = None):
        self.spec = spec
        if stds is None:
            stds = np.maximum(relative_std * np.abs(spec.defaults), 1e-6)
        self.stds = np.asarray(stds, dtype=np.float64)
        if self.stds.shape != (spec.n,):
            raise ValueError("ClosurePrior: stds length must match the spec")
        self.fd_coupling = fd_coupling

    def log_prior(self, theta) -> float:
        theta = np.asarray(theta, dtype=np.float64)
        if not self.spec.in_bounds(theta):
            return -np.inf
        z = (theta - self.spec.defaults) / self.stds
        lp = -0.5 * float(np.sum(z * z))
        if self.fd_coupling is not None:
            lp += float(self.fd_coupling.log_density(theta, self.spec))
        return lp

    def sample(self, n: int = 1, rng=None) -> np.ndarray:
        """Draw n samples by per-dimension truncated-normal rejection.

        The defaults lie inside the box, so rejection terminates; the box is wide
        relative to the prior width in the low-dimensional coefficient spaces used
        here (2 to 11 dims), as in the existing priors.Prior.
        """
        rng = np.random.default_rng() if rng is None else rng
        out = np.empty((n, self.spec.n))
        for i in range(n):
            for j in range(self.spec.n):
                lo, hi, mu, sd = (self.spec.lower[j], self.spec.upper[j],
                                  self.spec.defaults[j], self.stds[j])
                s = rng.normal(mu, sd)
                while s < lo or s > hi:
                    s = rng.normal(mu, sd)
                out[i, j] = s
        return out


class Prediction:
    """Predicted statistics from one forward evaluation (eta = H(theta))."""

    def __init__(self, statistics, status=EvaluationStatus.Unknown,
                 log_likelihood=None, metadata=None):
        self.statistics = np.asarray(statistics, dtype=np.float64)
        self.status = EvaluationStatus.coerce(status)
        self.log_likelihood = log_likelihood
        self.metadata = dict(metadata) if metadata else {}

    @property
    def converged(self) -> bool:
        return (self.status.is_usable() and self.statistics.size > 0
                and bool(np.all(np.isfinite(self.statistics))))


class Likelihood(ABC):
    """The likelihood hook: maps parameters to predicted statistics.

    ``predict(theta)`` returns a Prediction whose ``statistics`` (eta) feed the
    Kennedy-O'Hagan model-form likelihood, y = eta + delta + epsilon. A closure is
    bound to a benchmark (the data) to produce a concrete Likelihood.
    """

    @abstractmethod
    def predict(self, theta) -> Prediction:
        """Map a parameter vector to predicted statistics + a status."""

    @abstractmethod
    def parameter_spec(self) -> ParameterSpec:
        """The spec of the parameters this likelihood accepts."""

    def log_likelihood(self, theta) -> float:
        """Default: a converged Prediction's own log_likelihood, else -inf.

        KOH-based likelihoods override this to add the marginalised model-form
        discrepancy term.
        """
        pred = self.predict(theta)
        if not pred.converged or pred.log_likelihood is None:
            return -np.inf
        value = float(pred.log_likelihood)
        return value if np.isfinite(value) else -np.inf
