"""
Precomputed High-Mach Ensemble Demo
====================================
Phase 10 infrastructure hardening — demonstrating PrecomputedEnsembleForwardModel.

This script shows how to:
1. Build a synthetic high-Mach ensemble (theta, predictions) without any CFD solver.
2. Save it as an NPZ file in the documented format.
3. Load it via PrecomputedEnsembleForwardModel.
4. Run BayesianInferenceKOH using the precomputed data.
5. Save posterior summaries.

The ensemble is ENTIRELY SYNTHETIC — it uses the same parametric SBLI model
used in scramjet_calibration_demo.py, not a real high-Mach CFD solver.  When
real high-Mach data or external CFD ensembles are available, replace the
ensemble NPZ file with one generated by the real solver — no other code changes
are needed.

Expected NPZ format
-------------------
    theta:       shape (n_samples, d_theta) — parameter vectors
    predictions: shape (n_samples, n_obs)  — corresponding predictions
    param_names: array of d_theta strings  — parameter names (optional)
    obs_locations: array of n_obs floats   — spatial location of each observable

Usage
-----
    python precomputed_high_mach_ensemble_demo.py --quick -o /tmp/demo_out
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

# ---------------------------------------------------------------------------
# Synthetic SBLI analytic model (same as scramjet_calibration_demo)
# ---------------------------------------------------------------------------
X_SHOCK, X_SEP, X_REAT = 0.40, 0.35, 0.65
_OBS_X = np.linspace(0.0, 1.0, 8)   # 8 wall stations


def _cp(x, a1, beta_star):
    shock = 0.5 * (1 + np.tanh((x - X_SHOCK) / 0.05))
    dip   = -0.05 * np.exp(-((x - X_SEP) / 0.05) ** 2)
    return (0.3 + 0.4 * a1 / 0.31) * shock + dip


def _cf(x, a1, beta_star):
    base = 0.002 * beta_star / 0.09
    sep  = -0.0015 * np.exp(-((x - X_SEP)  / 0.06) ** 2)
    reat =  0.0010 * np.exp(-((x - X_REAT) / 0.08) ** 2)
    return base + sep + reat


def _predict(theta):
    """Return concatenated Cp+Cf predictions at _OBS_X for given (a1, betaStar)."""
    a1, bs = float(theta[0]), float(theta[1])
    return np.concatenate([_cp(_OBS_X, a1, bs), _cf(_OBS_X, a1, bs)])


# ---------------------------------------------------------------------------
# Build synthetic ensemble
# ---------------------------------------------------------------------------

def build_ensemble(n_samples: int, rng_seed: int = 0):
    rng   = np.random.default_rng(rng_seed)
    lower = np.array([0.22, 0.06])
    upper = np.array([0.45, 0.13])

    # Latin-hypercube
    X_lhc = np.empty((n_samples, 2))
    for j in range(2):
        perm = rng.permutation(n_samples)
        X_lhc[:, j] = lower[j] + (upper[j] - lower[j]) * (perm + rng.random(n_samples)) / n_samples

    rows_X, rows_Y = [], []
    for theta in X_lhc:
        preds = _predict(theta)
        if np.all(np.isfinite(preds)):
            rows_X.append(theta)
            rows_Y.append(preds)

    return np.array(rows_X), np.array(rows_Y)


def save_ensemble(out_dir: Path, n_samples: int, rng_seed: int = 0) -> Path:
    """Build and save ensemble NPZ in the documented format."""
    X, Y = build_ensemble(n_samples, rng_seed)
    n_obs = len(_OBS_X) * 2  # Cp + Cf at each station
    obs_locations = np.concatenate([_OBS_X, _OBS_X])

    path = out_dir / "high_mach_ensemble.npz"
    np.savez(
        str(path),
        X=X,
        Y=Y,
        param_names=np.array(["a1", "betaStar"]),
        obs_locations=obs_locations,
    )
    print(f"  Saved ensemble: {len(X)} samples × {n_obs} obs → {path}")
    return path


# ---------------------------------------------------------------------------
# Run inference
# ---------------------------------------------------------------------------

def run_demo(out_dir: Path, quick: bool = False):
    import sys
    sys.path.insert(0, str(Path(__file__).parent.parent))

    from forward_model_interface import PrecomputedEnsembleForwardModel
    from bayesian_inference import BayesianInferenceKOH, Prior, KOHLikelihood

    out_dir.mkdir(parents=True, exist_ok=True)

    n_ensemble = 40 if quick else 150
    n_walkers  = 8  if quick else 24
    n_steps    = 200 if quick else 1000
    burn_in    = 50  if quick else 300

    print("\n[1/5] Building synthetic ensemble ...")
    ens_path = save_ensemble(out_dir, n_samples=n_ensemble)

    print("[2/5] Loading PrecomputedEnsembleForwardModel ...")
    fm = PrecomputedEnsembleForwardModel.from_npz(ens_path)
    print(f"      {fm.n_samples} samples, {fm.n_outputs} outputs")
    print(f"      param names: {fm.parameter_names()}")

    # "True" generating parameters and synthetic observations
    a1_true, bs_true = 0.31, 0.09
    rng = np.random.default_rng(7)
    obs_vals  = _predict([a1_true, bs_true])
    obs_sigma = np.abs(obs_vals) * 0.03 + 1e-6
    obs_vals += rng.standard_normal(len(obs_vals)) * obs_sigma
    obs_locs  = np.concatenate([_OBS_X, _OBS_X])

    print("[3/5] Setting up KOH likelihood (diagonal discrepancy) ...")
    prior = Prior(
        means=[0.31, 0.09],
        stds=[0.05, 0.015],
        lower=[0.20, 0.05],
        upper=[0.50, 0.15],
    )
    koh = KOHLikelihood(
        obs_locations=obs_locs,
        obs_values=obs_vals,
        obs_sigmas=obs_sigma,
        mode="diagonal",
    )
    param_set = {
        "defaults": [0.31, 0.09],
        "lower":    [0.20, 0.05],
        "upper":    [0.50, 0.15],
        "names":    ["a1", "betaStar"],
    }

    bi = BayesianInferenceKOH(
        forward_model=fm,
        param_set=param_set,
        koh_likelihood=koh,
        theta_prior=prior,
    )

    print("[4/5] Running ensemble → surrogate → MCMC ...")
    bi.run_ensemble(n_samples=n_ensemble, verbose=False)
    bi.train_surrogate(verbose=False)
    bi.run_mcmc(n_walkers=n_walkers, n_steps=n_steps,
                burn_in=burn_in, verbose=False)

    print("[5/5] Saving results ...")
    summary = bi.posterior_summary()

    # Record how far the posterior mean is from the truth
    a1_z     = abs(summary["a1"]["mean"] - a1_true) / max(summary["a1"]["std"], 1e-6)
    bs_z     = abs(summary["betaStar"]["mean"] - bs_true) / max(summary["betaStar"]["std"], 1e-6)
    summary["_true"] = {"a1": a1_true, "betaStar": bs_true}
    summary["_z"]    = {"a1": a1_z, "betaStar": bs_z}

    (out_dir / "posterior_summary.json").write_text(json.dumps(summary, indent=2))

    print(f"\n  a1:       truth={a1_true:.3f}  post μ={summary['a1']['mean']:.3f}"
          f"  σ={summary['a1']['std']:.4f}  |z|={a1_z:.2f}")
    print(f"  betaStar: truth={bs_true:.3f}  post μ={summary['betaStar']['mean']:.4f}"
          f"  σ={summary['betaStar']['std']:.5f}  |z|={bs_z:.2f}")

    # Document the expected NPZ format for future external CFD ensembles
    format_doc = {
        "description": (
            "Expected NPZ format for PrecomputedEnsembleForwardModel. "
            "Replace 'X' and 'Y' with outputs from your external CFD solver. "
            "This is a synthetic demo — not real high-Mach data."
        ),
        "keys": {
            "X":             "shape (n_samples, d_theta) — parameter vectors",
            "Y":             "shape (n_samples, n_obs)  — predictions",
            "param_names":   "array of d_theta strings  — parameter names",
            "obs_locations": "array of n_obs floats — spatial location per observable",
        },
        "notes": [
            "Failed runs should be excluded before saving (no NaN rows in Y).",
            "Success/status flags are optional metadata — not needed by the loader.",
            "n_samples must be >= 10 to train the GP surrogate.",
            "For SU2/OpenFOAM/FUN3D: run solver at each X row, collect predictions.",
        ],
    }
    (out_dir / "ensemble_format_documentation.json").write_text(
        json.dumps(format_doc, indent=2)
    )

    print(f"\nOutputs written to: {out_dir}")
    print("  posterior_summary.json")
    print("  ensemble_format_documentation.json")
    print("  high_mach_ensemble.npz")
    print("\nNOTE: This is a SYNTHETIC demonstration. The ensemble uses a")
    print("      parametric analytic model, not a real high-Mach CFD solver.")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--quick", action="store_true",
                        help="Reduced ensemble/MCMC budget for CI testing")
    parser.add_argument("-o", "--out-dir", default="outputs/precomputed_ensemble_demo",
                        help="Output directory")
    args = parser.parse_args()

    run_demo(out_dir=Path(args.out_dir), quick=args.quick)


if __name__ == "__main__":
    main()
